# development: &default
#   #es_bin: '../elasticsearch-6.2.3/bin/elasticsearch'
#   # host: 'http://localhost:9200'
#   port: '9200'
# test:
#   es_bin: '../elasticsearch-6.2.3/bin/elasticsearch'
#   host: 'http://localhost:9250'
#   port: '9250'
# staging:
#   <<: *default
# production:
#   es_bin: '../elasticsearch-6.2.3/bin/elasticsearch'
#   host: 'http://localhost:9400'
#   port: '9400'
development: &default
  transport_options:
    request:
      timeout: !!integer 10000
